# If you are not sure what all these fields mean, please refer our documentation here:
# https://evalai.readthedocs.io/en/latest/configuration.html
title: Multimodal Reasoning Competition
short_description: MRC
description: templates/description.html
evaluation_details: templates/evaluation_details.html
terms_and_conditions: templates/terms_and_conditions.html
image: logo1.png
submission_guidelines: templates/submission_guidelines.html
leaderboard_description: For different tracks, please refer to the evaluation tab for their selected metrics.
evaluation_script: evaluation_script.zip
remote_evaluation: False
start_date: 2025-05-01 00:00:00
end_date: 2025-06-15 23:59:59
published: True
tags: 
  - deep-learning
  - computer-vision
leaderboard:
  - id: 1
    schema:
      {
        "labels": ["ACC"],
        "default_order_by": "ACC",
        "metadata": {
        }
      }

challenge_phases:
  - id: 1
    name: VG-RS
    description: templates/challenge_phase_1_description.html
    leaderboard_public: False
    is_public: False
    challenge: 1
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2025-05-01 00:00:00
    end_date: 2025-06-15 23:59:59
    test_annotation_file: annotations/VG_RS_testsplit.json
    codename: VG-RS
    max_submissions_per_day: 5000
    max_submissions_per_month: 5000
    max_submissions: 5000
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"
  - id: 2
    name: VQA-SA
    description: templates/challenge_phase_2_description.html
    leaderboard_public: True
    is_public: False
    challenge: 2
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2025-05-01 00:00:00
    end_date: 2025-06-15 23:59:59
    test_annotation_file: annotations/VQA_SA_testsplit.json
    codename: VQA-SA
    max_submissions_per_day: 5000
    max_submissions_per_month: 5000
    max_submissions: 5000
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"
  - id: 3
    name: VR-Ads
    description: templates/challenge_phase_3_description.html
    leaderboard_public: True
    is_public: False
    challenge: 3
    is_active: True
    max_concurrent_submissions_allowed: 3
    allowed_email_ids: []
    disable_logs: False
    is_submission_public: True
    start_date: 2025-05-01 00:00:00
    end_date: 2025-06-15 23:59:59
    test_annotation_file: annotations/VR_Ads_testsplit.json
    codename: VR-Ads
    max_submissions_per_day: 5000
    max_submissions_per_month: 5000
    max_submissions: 50000
    is_restricted_to_select_one_submission: True
    is_partial_submission_evaluation_enabled: False
    allowed_submission_file_types: ".json"

dataset_splits:
  # - id: 1
  #   name: Train Split
  #   codename: train_split
  - id: 1
    name: Test Split
    codename: test_split
  # - id: 3
  #   name: VR-Ads Split
  #   codename: vrads_split
    

challenge_phase_splits:
  - challenge_phase_id: 1
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
  - challenge_phase_id: 2
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    showeceution_time: True
    show_leaderboard_by_latest_submission: True
  - challenge_phase_id: 3
    leaderboard_id: 1
    dataset_split_id: 1
    visibility: 3
    leaderboard_decimal_precision: 2
    is_leaderboard_order_descending: True
    show_execution_time: True
    show_leaderboard_by_latest_submission: True
